language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - hhvm # on Trusty only
  - nightly

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-exif php5-gd
  - composer install

script:
  - composer run-script test
