language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - hhvm # on Trusty only
  - nightly

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes php5-gd
  - composer install

script:
  - composer run-script test
