language: php

notifications:
    email: elfimov@gmail.com

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: PHPUNIT_VERSION=6.*
        - php: 7.0
          env: PHPUNIT_VERSION=6.*
        - php: 5.6
          env: PHPUNIT_VERSION=5.*
        - php: 5.5
          env: PHPUNIT_VERSION=4.*
        - php: 5.4
          env: PHPUNIT_VERSION=4.*
        - php: hhvm
          env: PHPUNIT_VERSION=4.*
          dist: trusty
          group: edge

before_install:
  - sudo apt-get update > /dev/null
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer remove phpunit/phpunit --dev; composer require phpunit/phpunit:${PHPUNIT_VERSION} --dev --ignore-platform-reqs --no-update; fi;

install:
  - sudo apt-get install -y --force-yes php5-gd
  - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
  - composer run-script test
